In [1]:
import numpy as np

In [2]:
#通过数组初始化numpy array
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
b = np.array([[1,2,3]])
b.shape

(1, 3)

In [5]:
## 通过np自带的方法初始化arrays
np.zeros((1,3))

array([[0., 0., 0.]])

In [9]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((12))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full((2,3,8),7)

array([[[7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7, 7, 7]]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3)

array([0.15198736, 0.33735379, 0.18117387])

In [22]:
np.random.random((1,3))

array([[0.57871722, 0.88573068, 0.84810245]])

In [26]:
### slice
a = np.arange(15)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
b = a.reshape((3,5))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
b[:2,1:3]

array([[1, 2],
       [6, 7]])

In [39]:
a[:2]

array([0, 1])

In [44]:
b[1, :]

array([5, 6, 7, 8, 9])

In [45]:
b[1:2,:]

array([[5, 6, 7, 8, 9]])

In [47]:
### colum
b[:,1]

array([ 1,  6, 11])

In [49]:
### 组合索引
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
b[[1,0,1],[1,2,3]]
## equal b[1,1] b[0,2] b[1,3]

array([6, 2, 8])

In [51]:
##使用组合索引选择矩阵中的每一行的一个元素
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
index_col = np.array([0,1,0])
index_row = np.arange((3)) 


In [65]:
b[index_row, index_col]

array([ 0,  6, 10])

In [62]:
index_row

array([0, 1])

In [66]:
b[index_row, index_col] += 10

In [67]:
b

array([[10,  1,  2,  3,  4],
       [ 5, 16,  7,  8,  9],
       [20, 11, 12, 13, 14]])

In [69]:
通过boolean选择index
a = np.arange(6)

In [72]:
b = a.reshape(3,2)

In [74]:
bool_idx = (b>2)

In [77]:
bool_idx

array([[False, False],
       [False,  True],
       [ True,  True]])

In [80]:
## remove bool_idx equal false
b[bool_idx]

array([3, 4, 5])

In [81]:
## 数据类型
x = np.array([1,2], dtype=np.int64)

In [82]:
x

array([1, 2])

In [83]:
x.dtype

dtype('int64')

In [84]:
### 数学运算
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [85]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [86]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [88]:
np.multiply(x,y)  ##elementwirse product

array([[ 5, 12],
       [21, 32]])

In [89]:
np.dot(x,y)  ## matrix product

array([[19, 22],
       [43, 50]])

In [90]:
x * y ### elementwise product

array([[ 5, 12],
       [21, 32]])

In [91]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [92]:
v = np.array([10,11])
w = np.array([20,30])

In [94]:
np.dot(v,w)  ## inner product of vector

530

In [95]:
v.dot(w)

530

In [96]:
x.shape

(2, 2)

In [97]:
v.shape

(2,)

In [98]:
x.dot(v)

array([32, 74])

In [99]:
x

array([[1, 2],
       [3, 4]])

In [100]:
v

array([10, 11])

In [108]:
x = np.arange(15)

In [109]:
y = x.reshape(5,3)

In [110]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [111]:
np.sum(y,axis=0)  ## col

array([30, 35, 40])

In [112]:
np.sum(y, axis=1)  ## row

array([ 3, 12, 21, 30, 39])

In [114]:
## 转置
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [115]:
y.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [121]:
### 广播
x = np.arange(12)
y = x.reshape(3,4)
z = np.arange(4)

In [122]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
z

array([0, 1, 2, 3])

In [124]:
y + z

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [129]:
## 创建一个同维度的空矩阵
w = np.empty_like(y)

In [130]:
for i in range(y.shape[0]):
    w[i,:] = y[i,:] + z

In [131]:
w

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [136]:
zz = np.tile(z,(3,1))  ## stacking z

In [137]:
zz

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [138]:
zz + y

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [140]:
### example
v = np.array([1,2,3])
w = np.array([4,5])

In [143]:
v.shape

(3,)

In [144]:
w.shape

(2,)

In [147]:
## (3,1) * (2)
## (3,2) * (2,1)
v.reshape((3,1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [148]:
v.reshape((3,1)) 

array([[1],
       [2],
       [3]])

In [150]:
v

array([1, 2, 3])

In [152]:
x = np.arange(6).reshape((2,3))

In [153]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [154]:
## (2,3) + (3,) = (2,3)
print(x+ v)  

[[1 3 5]
 [4 6 8]]


In [156]:
## (2,3) + (2,)
print(x.T + w)

[[ 4  8]
 [ 5  9]
 [ 6 10]]


In [158]:
x  + w.reshape((2,1))

array([[ 4,  5,  6],
       [ 8,  9, 10]])